// Mocks generated by Mockito 5.4.6 from annotations
// in opus_dart/test/opus_dart_mock_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:ffi' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:opus_dart/wrappers/opus_decoder.dart' as _i2;
import 'package:opus_dart/wrappers/opus_encoder.dart' as _i5;
import 'package:opus_dart/wrappers/opus_libinfo.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [OpusDecoderFunctions].
///
/// See the documentation for Mockito's code generation for more information.
class MockOpusDecoderFunctions extends _i1.Mock
    implements _i2.OpusDecoderFunctions {
  MockOpusDecoderFunctions() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int opus_decoder_get_size(int? channels) => (super.noSuchMethod(
        Invocation.method(
          #opus_decoder_get_size,
          [channels],
        ),
        returnValue: 0,
      ) as int);

  @override
  _i3.Pointer<_i2.OpusDecoder> opus_decoder_create(
    int? Fs,
    int? channels,
    _i3.Pointer<_i3.Int32>? error,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #opus_decoder_create,
          [
            Fs,
            channels,
            error,
          ],
        ),
        returnValue: _i4.dummyValue<_i3.Pointer<_i2.OpusDecoder>>(
          this,
          Invocation.method(
            #opus_decoder_create,
            [
              Fs,
              channels,
              error,
            ],
          ),
        ),
      ) as _i3.Pointer<_i2.OpusDecoder>);

  @override
  int opus_decoder_init(
    _i3.Pointer<_i2.OpusDecoder>? st,
    int? Fs,
    int? channels,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #opus_decoder_init,
          [
            st,
            Fs,
            channels,
          ],
        ),
        returnValue: 0,
      ) as int);

  @override
  int opus_decode(
    _i3.Pointer<_i2.OpusDecoder>? st,
    _i3.Pointer<_i3.Uint8>? data,
    int? len,
    _i3.Pointer<_i3.Int16>? pcm,
    int? frame_size,
    int? decode_fec,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #opus_decode,
          [
            st,
            data,
            len,
            pcm,
            frame_size,
            decode_fec,
          ],
        ),
        returnValue: 0,
      ) as int);

  @override
  int opus_decode_float(
    _i3.Pointer<_i2.OpusDecoder>? st,
    _i3.Pointer<_i3.Uint8>? data,
    int? len,
    _i3.Pointer<_i3.Float>? pcm,
    int? frame_size,
    int? decode_fec,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #opus_decode_float,
          [
            st,
            data,
            len,
            pcm,
            frame_size,
            decode_fec,
          ],
        ),
        returnValue: 0,
      ) as int);

  @override
  void opus_decoder_destroy(_i3.Pointer<_i2.OpusDecoder>? st) =>
      super.noSuchMethod(
        Invocation.method(
          #opus_decoder_destroy,
          [st],
        ),
        returnValueForMissingStub: null,
      );

  @override
  int opus_packet_parse(
    _i3.Pointer<_i3.Uint8>? data,
    int? len,
    _i3.Pointer<_i3.Uint8>? out_toc,
    _i3.Pointer<_i3.Uint8>? frames,
    int? size,
    _i3.Pointer<_i3.Int32>? payload_offset,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #opus_packet_parse,
          [
            data,
            len,
            out_toc,
            frames,
            size,
            payload_offset,
          ],
        ),
        returnValue: 0,
      ) as int);

  @override
  int opus_packet_get_bandwidth(_i3.Pointer<_i3.Uint8>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #opus_packet_get_bandwidth,
          [data],
        ),
        returnValue: 0,
      ) as int);

  @override
  int opus_packet_get_samples_per_frame(
    _i3.Pointer<_i3.Uint8>? data,
    int? Fs,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #opus_packet_get_samples_per_frame,
          [
            data,
            Fs,
          ],
        ),
        returnValue: 0,
      ) as int);

  @override
  int opus_packet_get_nb_channels(_i3.Pointer<_i3.Uint8>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #opus_packet_get_nb_channels,
          [data],
        ),
        returnValue: 0,
      ) as int);

  @override
  int opus_packet_get_nb_frames(
    _i3.Pointer<_i3.Uint8>? packet,
    int? len,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #opus_packet_get_nb_frames,
          [
            packet,
            len,
          ],
        ),
        returnValue: 0,
      ) as int);

  @override
  int opus_packet_get_nb_samples(
    _i3.Pointer<_i3.Uint8>? packet,
    int? len,
    int? Fs,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #opus_packet_get_nb_samples,
          [
            packet,
            len,
            Fs,
          ],
        ),
        returnValue: 0,
      ) as int);

  @override
  int opus_decoder_get_nb_samples(
    _i3.Pointer<_i2.OpusDecoder>? dec,
    _i3.Pointer<_i3.Uint8>? packet,
    int? len,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #opus_decoder_get_nb_samples,
          [
            dec,
            packet,
            len,
          ],
        ),
        returnValue: 0,
      ) as int);

  @override
  void opus_pcm_soft_clip(
    _i3.Pointer<_i3.Float>? pcm,
    int? frame_size,
    int? channels,
    _i3.Pointer<_i3.Float>? softclip_mem,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #opus_pcm_soft_clip,
          [
            pcm,
            frame_size,
            channels,
            softclip_mem,
          ],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [OpusEncoderFunctions].
///
/// See the documentation for Mockito's code generation for more information.
class MockOpusEncoderFunctions extends _i1.Mock
    implements _i5.OpusEncoderFunctions {
  MockOpusEncoderFunctions() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int opus_encoder_get_size(int? channels) => (super.noSuchMethod(
        Invocation.method(
          #opus_encoder_get_size,
          [channels],
        ),
        returnValue: 0,
      ) as int);

  @override
  _i3.Pointer<_i5.OpusEncoder> opus_encoder_create(
    int? Fs,
    int? channels,
    int? application,
    _i3.Pointer<_i3.Int32>? error,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #opus_encoder_create,
          [
            Fs,
            channels,
            application,
            error,
          ],
        ),
        returnValue: _i4.dummyValue<_i3.Pointer<_i5.OpusEncoder>>(
          this,
          Invocation.method(
            #opus_encoder_create,
            [
              Fs,
              channels,
              application,
              error,
            ],
          ),
        ),
      ) as _i3.Pointer<_i5.OpusEncoder>);

  @override
  int opus_encoder_init(
    _i3.Pointer<_i5.OpusEncoder>? st,
    int? Fs,
    int? channels,
    int? application,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #opus_encoder_init,
          [
            st,
            Fs,
            channels,
            application,
          ],
        ),
        returnValue: 0,
      ) as int);

  @override
  int opus_encode(
    _i3.Pointer<_i5.OpusEncoder>? st,
    _i3.Pointer<_i3.Int16>? pcm,
    int? frame_size,
    _i3.Pointer<_i3.Uint8>? data,
    int? max_data_bytes,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #opus_encode,
          [
            st,
            pcm,
            frame_size,
            data,
            max_data_bytes,
          ],
        ),
        returnValue: 0,
      ) as int);

  @override
  int opus_encode_float(
    _i3.Pointer<_i5.OpusEncoder>? st,
    _i3.Pointer<_i3.Float>? pcm,
    int? frame_size,
    _i3.Pointer<_i3.Uint8>? data,
    int? max_data_bytes,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #opus_encode_float,
          [
            st,
            pcm,
            frame_size,
            data,
            max_data_bytes,
          ],
        ),
        returnValue: 0,
      ) as int);

  @override
  void opus_encoder_destroy(_i3.Pointer<_i5.OpusEncoder>? st) =>
      super.noSuchMethod(
        Invocation.method(
          #opus_encoder_destroy,
          [st],
        ),
        returnValueForMissingStub: null,
      );

  @override
  int opus_encoder_ctl(
    _i3.Pointer<_i5.OpusEncoder>? st,
    int? request,
    int? va,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #opus_encoder_ctl,
          [
            st,
            request,
            va,
          ],
        ),
        returnValue: 0,
      ) as int);
}

/// A class which mocks [OpusLibInfoFunctions].
///
/// See the documentation for Mockito's code generation for more information.
class MockOpusLibInfoFunctions extends _i1.Mock
    implements _i6.OpusLibInfoFunctions {
  MockOpusLibInfoFunctions() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Pointer<_i3.Uint8> opus_get_version_string() => (super.noSuchMethod(
        Invocation.method(
          #opus_get_version_string,
          [],
        ),
        returnValue: _i4.dummyValue<_i3.Pointer<_i3.Uint8>>(
          this,
          Invocation.method(
            #opus_get_version_string,
            [],
          ),
        ),
      ) as _i3.Pointer<_i3.Uint8>);

  @override
  _i3.Pointer<_i3.Uint8> opus_strerror(int? error) => (super.noSuchMethod(
        Invocation.method(
          #opus_strerror,
          [error],
        ),
        returnValue: _i4.dummyValue<_i3.Pointer<_i3.Uint8>>(
          this,
          Invocation.method(
            #opus_strerror,
            [error],
          ),
        ),
      ) as _i3.Pointer<_i3.Uint8>);
}
